import type { Symbol } from '@/types/market-data';

export const DEFAULT_SYMBOLS: Symbol[] = [
  // ==================== FUTURES ====================
  {
    id: 'ES',
    name: 'ES',
    displayName: 'E-mini S&P 500',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.25,
    pointValue: 50,       // $50 per full index point
    tickValue: 12.50,     // 0.25 * $50 = $12.50 per tick
    marginRequirement: 12650,
    description: 'E-mini S&P 500 Index Futures (Continuous)',
    sessionType: 'CME_ETH',
  },
  {
    id: 'MES',
    name: 'MES',
    displayName: 'Micro E-mini S&P 500',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.25,
    pointValue: 5,        // $5 per full index point
    tickValue: 1.25,      // 0.25 * $5 = $1.25 per tick
    marginRequirement: 1265,
    description: 'Micro E-mini S&P 500 Futures',
    sessionType: 'CME_ETH',
  },
  {
    id: 'NQ',
    name: 'NQ',
    displayName: 'E-mini Nasdaq 100',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.25,
    pointValue: 20,       // $20 per full index point
    tickValue: 5.00,      // 0.25 * $20 = $5.00 per tick
    marginRequirement: 18700,
    description: 'E-mini Nasdaq-100 Index Futures (Continuous)',
    sessionType: 'CME_ETH',
  },
  {
    id: 'MNQ',
    name: 'MNQ',
    displayName: 'Micro E-mini Nasdaq 100',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.25,
    pointValue: 2,        // $2 per full index point
    tickValue: 0.50,      // 0.25 * $2 = $0.50 per tick
    marginRequirement: 1870,
    description: 'Micro E-mini Nasdaq-100 Futures',
    sessionType: 'CME_ETH',
  },
  {
    id: 'YM',
    name: 'YM',
    displayName: 'E-mini Dow Jones ($5)',
    exchange: 'CBOT',
    assetClass: 'futures',
    pricePrecision: 0,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 1.00,
    pointValue: 5,        // $5 per index point
    tickValue: 5.00,      // 1.00 * $5 = $5.00 per tick
    marginRequirement: 9350,
    description: 'E-mini Dow Jones Industrial Average ($5 Multiplier)',
    sessionType: 'CME_ETH',
  },
  {
    id: 'MYM',
    name: 'MYM',
    displayName: 'Micro E-mini Dow Jones',
    exchange: 'CBOT',
    assetClass: 'futures',
    pricePrecision: 0,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 1.00,
    pointValue: 0.50,     // $0.50 per index point
    tickValue: 0.50,      // 1.00 * $0.50 = $0.50 per tick
    marginRequirement: 935,
    description: 'Micro E-mini Dow Jones Futures',
    sessionType: 'CME_ETH',
  },
  {
    id: 'RTY',
    name: 'RTY',
    displayName: 'E-mini Russell 2000',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.10,
    pointValue: 50,       // $50 per index point
    tickValue: 5.00,      // 0.10 * $50 = $5.00 per tick
    marginRequirement: 7150,
    description: 'E-mini Russell 2000 Index Futures',
    sessionType: 'CME_ETH',
  },
  {
    id: 'M2K',
    name: 'M2K',
    displayName: 'Micro E-mini Russell 2000',
    exchange: 'CME',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.10,
    pointValue: 5,        // $5 per index point
    tickValue: 0.50,      // 0.10 * $5 = $0.50 per tick
    marginRequirement: 715,
    description: 'Micro E-mini Russell 2000 Futures',
    sessionType: 'CME_ETH',
  },
  {
    id: 'GC',
    name: 'GC',
    displayName: 'Gold Futures (100 oz)',
    exchange: 'COMEX',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.10,
    pointValue: 100,      // $100 per 1.00 full point
    tickValue: 10.00,     // 0.10 * $100 = $10.00 per tick
    marginRequirement: 10450,
    description: 'Gold Futures (100 troy oz contract)',
    sessionType: 'CME_ETH',
  },
  {
    id: 'CL',
    name: 'CL',
    displayName: 'Crude Oil Futures (1,000 bbl)',
    exchange: 'NYMEX',
    assetClass: 'futures',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.01,
    pointValue: 1000,     // $1,000 per 1.00 full point
    tickValue: 10.00,     // 0.01 * $1,000 = $10.00 per tick
    marginRequirement: 6600,
    description: 'Light Sweet Crude Oil Futures (1,000 bbl)',
    sessionType: 'CME_ETH',
  },

  // ==================== FOREX ====================
  {
    id: 'EURUSD',
    name: 'EURUSD',
    displayName: 'EUR / USD',
    exchange: 'FX',
    assetClass: 'forex',
    pricePrecision: 5,
    quantityPrecision: 0,
    minQuantity: 1000,
    tickSize: 0.00001,
    pointValue: 100000,
    tickValue: 1.00,
    contractSize: 100000,
    description: 'Euro / US Dollar',
    sessionType: 'FOREX_24_5',
  },
  {
    id: 'GBPUSD',
    name: 'GBPUSD',
    displayName: 'GBP / USD',
    exchange: 'FX',
    assetClass: 'forex',
    pricePrecision: 5,
    quantityPrecision: 0,
    minQuantity: 1000,
    tickSize: 0.00001,
    pointValue: 100000,
    tickValue: 1.00,
    contractSize: 100000,
    description: 'British Pound / US Dollar',
    sessionType: 'FOREX_24_5',
  },
  {
    id: 'USDJPY',
    name: 'USDJPY',
    displayName: 'USD / JPY',
    exchange: 'FX',
    assetClass: 'forex',
    pricePrecision: 3,
    quantityPrecision: 0,
    minQuantity: 1000,
    tickSize: 0.001,
    pointValue: 100000,
    tickValue: 0.70,
    contractSize: 100000,
    description: 'US Dollar / Japanese Yen',
    sessionType: 'FOREX_24_5',
  },

  // ==================== CRYPTO ====================
  {
    id: 'BTCUSDT',
    name: 'BTCUSDT',
    displayName: 'BTC / USDT',
    exchange: 'BINANCE',
    assetClass: 'crypto',
    pricePrecision: 2,
    quantityPrecision: 4,
    minQuantity: 0.0001,
    tickSize: 0.10,
    pointValue: 1,
    tickValue: 0.10,
    description: 'Bitcoin / Tether Perpetual',
    sessionType: 'CRYPTO_24_7',
  },
  {
    id: 'ETHUSDT',
    name: 'ETHUSDT',
    displayName: 'ETH / USDT',
    exchange: 'BINANCE',
    assetClass: 'crypto',
    pricePrecision: 2,
    quantityPrecision: 3,
    minQuantity: 0.001,
    tickSize: 0.01,
    pointValue: 1,
    tickValue: 0.01,
    description: 'Ethereum / Tether Perpetual',
    sessionType: 'CRYPTO_24_7',
  },

  // ==================== STOCKS ====================
  {
    id: 'AAPL',
    name: 'AAPL',
    displayName: 'Apple Inc.',
    exchange: 'NASDAQ',
    assetClass: 'stocks',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.01,
    pointValue: 1,
    tickValue: 0.01,
    contractSize: 1,
    description: 'Apple Inc. Common Stock',
    sessionType: 'US_EQUITIES',
  },
  {
    id: 'NVDA',
    name: 'NVDA',
    displayName: 'NVIDIA Corp.',
    exchange: 'NASDAQ',
    assetClass: 'stocks',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.01,
    pointValue: 1,
    tickValue: 0.01,
    contractSize: 1,
    description: 'NVIDIA Corporation Common Stock',
    sessionType: 'US_EQUITIES',
  },
  {
    id: 'TSLA',
    name: 'TSLA',
    displayName: 'Tesla Inc.',
    exchange: 'NASDAQ',
    assetClass: 'stocks',
    pricePrecision: 2,
    quantityPrecision: 0,
    minQuantity: 1,
    tickSize: 0.01,
    pointValue: 1,
    tickValue: 0.01,
    contractSize: 1,
    description: 'Tesla Inc. Common Stock',
    sessionType: 'US_EQUITIES',
  },
];

export const DEFAULT_SYMBOL = DEFAULT_SYMBOLS[0]; // ES Futures default

export function getSymbolById(id: string): Symbol | undefined {
  return DEFAULT_SYMBOLS.find((s) => s.id.toUpperCase() === id.toUpperCase());
}
